spring:
  application:
    name: demo-sharding-jdbc


mybatis:
  type-aliases-package: com.example.demo.shardingjdbc.entity

datasource:
  primary:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
